name: Simple Test

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print current directory and files
      run: |
        pwd
        ls -la

    - name: Test python version
      run: |
        python --version
        echo "Тест успешно пройден!"
