name: Run Telegram Bot

on:
  workflow_dispatch: # Оставляем ручной запуск кнопкой
  schedule:
    - cron: '0 */5 * * *' # Запускать каждые 5 часов автоматически

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bot
        run: python bot.py
        
